Repository housingbayarea/bloom, pull requests merged in 2022-05, with the labels that each got.

#402 394/updated how it works copy
  sites/public/page_content/homepage_how_it_works.md
  sites/public/page_content/how_it_works.md
Labels: ready to merge

#404 feat: translation for fremont preference
  sites/partners/page_content/locale_overrides/general.json
  sites/public/page_content/locale_overrides/general.json
Labels: ready to merge

#406 401/sj new resouce
  sites/public/page_content/AdditionalResources.md
Labels: Ready for Review

#416 feat: creating Emeryville preference
  backend/core/src/migration/1650934163344-alameda-programs-and-preferences.ts
  sites/partners/page_content/locale_overrides/general.json
  sites/public/page_content/locale_overrides/general.json
Labels: Ready for Review

#415 fix: updated resource content
  sites/public/page_content/AdditionalResourcesSidebar.md
  sites/public/sentry.server.config.js
Labels: ready to merge

#418 fix: resource and translation updates
  sites/public/page_content/AdditionalResources.md
  sites/public/page_content/AdditionalResourcesSidebar.md
Labels: Ready for Review

#423 fix: updated contact info translations
  sites/public/page_content/AdditionalResourcesSidebar.md
Labels: Ready for Review

#422 393/how it works translations
  sites/public/page_content/homepage_how_it_works.md
  sites/public/page_content/how_it_works.md
  sites/public/page_content/locale_overrides/es.json
  sites/public/page_content/locale_overrides/vi.json
  sites/public/page_content/locale_overrides/zh.json
  sites/public/pages/index.tsx
Labels: question

#424 fix: reformatting and cleaning
  sites/public/page_content/locale_overrides/general.json
  sites/public/page_content/resources/AffordableRentalHousingList.md
  sites/public/page_content/resources/BayArea211.md
  sites/public/page_content/resources/CIH.md
  sites/public/page_content/resources/HAotCoSM.md
  sites/public/page_content/resources/HIPHousing.md
  sites/public/page_content/resources/HavenConnect.md
  sites/public/page_content/resources/HousingChoices.md
  sites/public/page_content/resources/ProjectSentinel.md
  sites/public/page_content/resources/SMCHousingSearch.md
  sites/public/page_content/resources/Sidebar.md
  sites/public/pages/additional-resources.tsx
  sites/public/src/RenderIf.tsx
  sites/public/src/Resource.tsx
Labels: ready to merge

#429 409/sj resource reformat
  sites/public/components/RenderIf.tsx
  sites/public/page_content/AdditionalResources.md
  sites/public/page_content/locale_overrides/es.json
  sites/public/page_content/locale_overrides/general.json
  sites/public/page_content/locale_overrides/vi.json
  sites/public/page_content/locale_overrides/zh.json
  sites/public/page_content/resources/affordableHousingSCC.md
  sites/public/page_content/resources/affordableHousingSJ.md
  sites/public/page_content/resources/alaCounty.md
  sites/public/page_content/resources/doorwayPortal.md
  sites/public/page_content/resources/homelessHotline.md
  sites/public/page_content/resources/housingChoices.md
  sites/public/page_content/resources/section8.md
  sites/public/page_content/resources/sfCounty.md
  sites/public/page_content/resources/sidebar.md
  sites/public/page_content/resources/smCounty.md
  sites/public/page_content/resources/unitedWay211.md
  sites/public/pages/additional-resources.tsx
  sites/public/src/RenderIf.tsx
  sites/public/src/Resource.tsx
Labels: ready to merge
