Repository housingbayarea/bloom, pull requests merged in 2022-11, with the labels that each got.

#523 fix: migration to fix multiselect translation bug
  backend/core/src/migration/1666583981588-multiselectTranslationFix.ts
Labels: ready to merge

#524 chore: add SJ confirmation email translations
  backend/core/src/migration/1666405530762-addSJWhatToExpectTranslations.ts
Labels: ready to merge

#533 fix: migration to fix multiselect translation bug
  backend/core/src/migration/1666583981588-multiselectTranslationFix.ts
Labels: 1 review needed

#512 3138/multiselect question x translation issue
  backend/core/src/multiselect-question/entities/multiselect-question.entity.ts
  backend/core/src/multiselect-question/multiselect-question.controller.ts
  backend/core/src/multiselect-question/types/multiselect-option.ts
  backend/core/src/translations/services/translations.service.ts
  backend/core/types/src/backend-swagger.ts
  sites/public/lib/helpers.tsx
  sites/public/pages/applications/review/terms.tsx
Labels: ready to merge

#537 fix: multiselect question x translation issue
  backend/core/src/multiselect-question/entities/multiselect-question.entity.ts
  backend/core/src/multiselect-question/multiselect-question.controller.ts
  backend/core/src/multiselect-question/types/multiselect-option.ts
  backend/core/src/translations/services/translations.service.ts
  backend/core/types/src/backend-swagger.ts
  sites/public/lib/helpers.tsx
  sites/public/pages/applications/review/terms.tsx
Labels: 1 review needed

#536 fix: remove the queue for afs processing on listing close
  backend/core/package.json
  backend/core/src/listings/listings.service.ts
  yarn.lock
Labels: ready to merge

#534 chore: add translations for Alameda What to Expect content
  sites/public/page_content/locale_overrides/es.json
  sites/public/page_content/locale_overrides/tl.json
  sites/public/page_content/locale_overrides/vi.json
  sites/public/page_content/locale_overrides/zh.json
  sites/public/styles/overrides.scss
Labels: ready to merge

#543 feat: release 2022-11-17
  backend/core/package.json
  backend/core/src/migration/1666405530762-addSJWhatToExpectTranslations.ts
  shared-helpers/src/Timeout.tsx
  sites/partners/pages/application/[id]/review.tsx
  sites/partners/pages/index.tsx
  sites/partners/pages/listings/[id]/applications/index.tsx
  sites/partners/pages/listings/[id]/applications/pending/index.tsx
  sites/partners/pages/listings/[id]/applications/resolved/index.tsx
  sites/partners/pages/settings/index.tsx
  sites/partners/src/ConfirmationModal.tsx
  sites/partners/src/applications/Aside.tsx
  sites/partners/src/applications/PaperApplicationForm/FormMember.tsx
  sites/partners/src/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
  sites/partners/src/listings/Aside.tsx
  sites/partners/src/listings/PaperListingForm/UnitForm.tsx
  sites/partners/src/listings/PaperListingForm/index.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/partners/src/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
  sites/partners/src/listings/PaperListingForm/sections/ListingPhoto.tsx
  sites/partners/src/listings/PaperListingForm/sections/LotteryResults.tsx
  sites/partners/src/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/partners/src/listings/PaperListingForm/sections/Units.tsx
  sites/partners/src/settings/PreferenceDeleteModal.tsx
  sites/partners/src/users/FormUserManage.tsx
  sites/partners/src/users/ReRequestConfirmation.tsx
  sites/public/pages/applications/start/choose-language.tsx
  sites/public/pages/create-account.tsx
  sites/public/pages/index.tsx
  sites/public/src/ConfirmationModal.tsx
  ui-components/package.json
  ui-components/src/blocks/ImageCard.tsx
  ui-components/src/global/vendor/ag_grid.scss
  ui-components/src/headers/PageHeader.scss
  ui-components/src/overlays/Drawer.stories.tsx
  ui-components/src/overlays/Modal.scss
  ui-components/src/overlays/Modal.stories.tsx
  ui-components/src/overlays/Modal.tsx
  ui-components/src/overlays/Overlay.tsx
  ui-components/src/page_components/sign-in/ResendConfirmationModal.tsx
  ui-components/src/tables/AgTable.tsx
  ui-components/tailwind.config.js
  yarn.lock
Labels: 2 reviews needed

#545 fix: updates per kathy finds
  backend/core/src/applications/services/csv-builder.service.ts
  backend/core/src/applications/services/csv-builder.spec.ts
  backend/core/src/migration/1666583981588-multiselectTranslationFix.ts
Labels: ready to merge

#552 feat: adding UUID validation
  backend/core/src/applications/applications.controller.ts
  backend/core/src/auth/controllers/user.controller.ts
  backend/core/src/listings/listings.controller.ts
  sites/partners/lib/hooks.ts
Labels: 2 reviews needed

#553 fix: migration update
  backend/core/src/migration/1666583981588-multiselectTranslationFix.ts
Labels: ready to merge

#550 fix: unit query separated from listing query
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/tests/listings.service.spec.ts
  backend/core/src/listings/views/config.ts
  backend/core/src/listings/views/view.spec.ts
Labels: 1 review needed

#540 fix: updates to a san jose resource card
  sites/public/page_content/jurisdiction_overrides/san_jose/resources/homelessHotline.md
Labels: ready to merge
