Repository housingbayarea/bloom, pull requests merged in 2022-08, with the labels that each got.

#460 fix: fix for big timeout on flagged set (#2946)
  backend/core/src/application-flagged-sets/application-flagged-sets.service.ts
  sites/partners/src/flags/flagSetCols.tsx
Labels: Ready for Review

#458 fix: updated email address
  sites/public/layouts/application.tsx
Labels: ready to merge

#459 feat: add How It Works and Get Assistance pages
  sites/public/.env.template
  sites/public/next.config.js
  sites/public/page_content/get_assistance.md
  sites/public/page_content/homepage_how_it_works.md
  sites/public/page_content/how_it_works.md
  sites/public/page_content/locale_overrides/es.json
  sites/public/page_content/locale_overrides/general.json
  sites/public/page_content/locale_overrides/vi.json
  sites/public/page_content/locale_overrides/zh.json
  sites/public/pages/_app.tsx
  sites/public/pages/get-assistance.tsx
  sites/public/pages/how-it-works.tsx
  sites/public/pages/index.tsx
  sites/public/styles/overrides.scss
Labels: ready to merge

#463 feat: adds new san jose ami charts
  backend/core/src/migration/1661352526487-sanJoseAmi.ts
  backend/core/src/seeder/seeds/ami-charts/san-jose-hcd-income-limits-2022.ts
  backend/core/src/seeder/seeds/ami-charts/san-jose-hud-home-2022.ts
Labels: 1 review needed
