Repository housingbayarea/bloom, pull requests merged in 2022-10, with the labels that each got.

#506 fix: remove lottery date from confirmation email
  backend/core/src/email/email.service.spec.ts
  backend/core/src/email/email.service.ts
Labels: 1 review needed

#508 feat: backend changes for what to expect changes
  backend/core/src/email/email.service.spec.ts
  backend/core/src/email/email.service.ts
  backend/core/src/listings/dto/listing-published-create.dto.ts
  backend/core/src/listings/dto/listing-published-update.dto.ts
  backend/core/src/listings/entities/listing.entity.ts
  backend/core/src/listings/listings.service.ts
  backend/core/src/listings/types/listing-availability-enum.ts
  backend/core/src/listings/types/listing-review-order-enum.ts
  backend/core/src/listings/views/config.ts
  backend/core/src/migration/1663104141106-new-confirmation-email-translations.ts
  backend/core/src/migration/1663959354563-new-listing-type-enum.ts
  backend/core/src/migration/1665528174645-email-reset-translations.ts
  backend/core/src/seeder/seeds/listings/listing-coliseum-seed.ts
  backend/core/src/seeder/seeds/listings/listing-triton-seed.ts
  backend/core/src/seeder/seeds/listings/shared.ts
  backend/core/src/shared/units-transformations.ts
  backend/core/src/shared/views/confirmation.hbs
  backend/core/src/translations/services/translations.service.ts
  backend/core/types/src/backend-swagger.ts
  shared-helpers/src/summaryTables.tsx
  sites/partners/__tests__/PaperListingForm/sections/DetailUnits.test.tsx
  sites/partners/__tests__/testHelpers.ts
  sites/partners/cypress/integration/03-listing.spec.ts
  sites/partners/src/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx
  sites/partners/src/listings/PaperListingDetails/sections/DetailUnits.tsx
  sites/partners/src/listings/PaperListingForm/formTypes.ts
  sites/partners/src/listings/PaperListingForm/formatters/AdditionalMetadataFormatter.ts
  sites/partners/src/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/partners/src/listings/PaperListingForm/sections/Units.tsx
  sites/public/lib/helpers.tsx
  sites/public/pages/applications/review/confirmation.tsx
  sites/public/pages/applications/review/terms.tsx
  sites/public/pages/applications/start/what-to-expect.tsx
  sites/public/src/ListingView.tsx
  ui-components/src/global/markdown.scss
  ui-components/src/locales/general.json
Labels: 2 reviews needed

#516 fix: update fremont family resources link
  sites/public/page_content/resources/fremontFamily.md
Labels: ready to merge

#522 chore: add SJ translations for What to Expect content
  sites/public/page_content/locale_overrides/es.json
  sites/public/page_content/locale_overrides/vi.json
  sites/public/page_content/locale_overrides/zh.json
  sites/public/styles/overrides.scss
Labels: ready to merge

#526 491/sj what to expect translations
  sites/public/page_content/locale_overrides/es.json
  sites/public/page_content/locale_overrides/vi.json
  sites/public/page_content/locale_overrides/zh.json
  sites/public/pages/applications/review/confirmation.tsx
Labels: ready to merge
