Repository housingbayarea/bloom, pull requests merged in 2024-11, with the labels that each got.

#796 release: update ami chart script (#4408)
  api/src/controllers/script-runner.controller.ts
  api/src/dtos/script-runner/ami-chart-update-import.dto.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge, release

#801 fix: moving express from dev dependencies (#4390)
  api/package.json
Labels: ready to merge

#681 fix: geocoding sj
  api/prisma/seed-staging.ts
  api/src/controllers/script-runner.controller.ts
  api/src/data/SanJoseDistrict1.json
  api/src/data/SanJoseDistrict10.json
  api/src/data/SanJoseDistrict2.json
  api/src/data/SanJoseDistrict3.json
  api/src/data/SanJoseDistrict4.json
  api/src/data/SanJoseDistrict5.json
  api/src/data/SanJoseDistrict6.json
  api/src/data/SanJoseDistrict7.json
  api/src/data/SanJoseDistrict8.json
  api/src/data/SanJoseDistrict9.json
  api/src/data/SanJoseRedlined.json
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  api/tsconfig.json
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/cypress/e2e/default/09-lottery.spec.ts
  sites/partners/src/components/settings/PreferenceDrawer.tsx
Labels: high priority, ready to merge

#800 fix: remove smc references in footers
  sites/public/src/page_content/jurisdiction_overrides/alameda/jurisdiction-footer-section.tsx
  sites/public/src/page_content/jurisdiction_overrides/san_jose/jurisdiction-footer-section.tsx
Labels: ready to merge

#802 feat: [GenAI] new listing gen ai export endpoint
  api/src/controllers/listing.controller.ts
  api/src/dtos/listings/listing-csv-query-params.dto.ts
  api/src/services/listing-csv-export.service.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge, genAI

#805 feat: gen ai endpoint units updates
  api/src/services/listing-csv-export.service.ts
Labels: 1 review needed

#804 fix: update retract modal copy (#4468)
  sites/partners/src/page_content/locale_overrides/general.json
Labels: ready to merge, release

#810 fix: reduce the view for user edit
  sites/partners/src/lib/hooks.ts
  sites/partners/src/pages/users/index.tsx
Labels: ready to merge

#811 fix: using fundamental view
  sites/partners/src/lib/hooks.ts
Labels: 1 review needed

#803 feat: programs on listings (#4412)
  api/src/controllers/script-runner.controller.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/types/backend-swagger.ts
  sites/public/src/components/listing/ListingView.tsx
  sites/public/styles/overrides.scss
Labels: ready to merge, release

#797 fix: listing duplicate fe (#4309)
  api/.env.template
  api/prisma/migrations/19_duplicate_listing_permissions/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed-helpers/jurisdiction-factory.ts
  api/src/dtos/jurisdictions/jurisdiction.dto.ts
  api/src/services/listing.service.ts
  api/test/integration/jurisdiction.e2e-spec.ts
  api/test/integration/permission-tests/helpers.ts
  shared-helpers/__tests__/testHelpers.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/.env.template
  sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
  sites/partners/next.config.js
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/listings/PaperListingForm/dialogs/CopyListingDialog.tsx
  sites/partners/src/page_content/locale_overrides/general.json
  sites/partners/src/pages/index.tsx
  sites/partners/src/pages/listings/[id]/index.tsx
  sites/partners/src/pages/settings/index.tsx
Labels: ready to merge, release

#813 feat: adding msq export, updating listing export for gen ai
  api/src/services/listing-csv-export.service.ts
Labels: 1 review needed, genAI

#806 feat: create feature flag table (#4475)
  api/prisma/migrations/20_create_feature_flag_table/migration.sql
  api/prisma/schema.prisma
Labels: ready to merge, release

#808 fix: return updated failed login attempts (#4474)
  api/src/passports/mfa.strategy.ts
  api/src/passports/single-use-code.strategy.ts
  api/src/utilities/passport-validator-utilities.ts
  api/test/unit/passports/passport-validator-utilities.spec.ts
Labels: ready to merge, release

#815 fix: handle copying app methods (#4491)
  api/src/services/listing.service.ts
Labels: ready to merge, release

#818 release: various Toast updates
  shared-helpers/src/auth/RequireLogin.tsx
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/utilities/MessageContext.ts
  sites/public/src/components/account/ConfirmationModal.tsx
  sites/public/src/pages/applications/review/summary.tsx
  sites/public/src/pages/applications/start/choose-language.tsx
Labels: ready to merge
