Repository housingbayarea/bloom, pull requests merged in 2024-09, with the labels that each got.

#757 release: opt out existing lotteries
  api/prisma/seed-helpers/listing-factory.ts
  api/prisma/seed-staging.ts
  api/src/controllers/script-runner.controller.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge, release

#756 release: auto publish lotteries
  api/.env.template
  api/src/controllers/listing.controller.ts
  api/src/controllers/lottery.controller.ts
  api/src/services/email.service.ts
  api/src/services/listing.service.ts
  api/src/services/lottery.service.ts
  api/src/utilities/cron-job-starter.ts
  api/test/integration/lottery.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/services/lottery.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/src/page_content/locale_overrides/general.json
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: ready to merge, release

#759 feat: add Live In Aid as household member relationship
  api/src/enums/applications/household-member-relationship-enum.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge

#753 fix: alphabetize all files
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/partners/src/page_content/locale_overrides/general.json
  sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/es.json
  sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/general.json
  sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/tl.json
  sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/vi.json
  sites/public/src/page_content/jurisdiction_overrides/alameda/locale_overrides/zh.json
  sites/public/src/page_content/jurisdiction_overrides/san_jose/locale_overrides/es.json
  sites/public/src/page_content/jurisdiction_overrides/san_jose/locale_overrides/general.json
  sites/public/src/page_content/jurisdiction_overrides/san_jose/locale_overrides/vi.json
  sites/public/src/page_content/jurisdiction_overrides/san_jose/locale_overrides/zh.json
  sites/public/src/page_content/jurisdiction_overrides/san_mateo/locale_overrides/es.json
  sites/public/src/page_content/jurisdiction_overrides/san_mateo/locale_overrides/general.json
  sites/public/src/page_content/jurisdiction_overrides/san_mateo/locale_overrides/vi.json
  sites/public/src/page_content/jurisdiction_overrides/san_mateo/locale_overrides/zh.json
  sites/public/src/page_content/locale_overrides/general.json
Labels: ready to merge

#763 release: listing duplication endpoint
  api/.env.template
  api/src/controllers/listing.controller.ts
  api/src/dtos/listings/listing-duplicate.dto.ts
  api/src/services/listing.service.ts
  api/src/services/lottery.service.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-admin.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-correct-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-juris-admin-wrong-juris.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-no-user.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-correct-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-partner-wrong-listing.e2e-spec.ts
  api/test/integration/permission-tests/permission-as-public.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/services/lottery.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: release

#768 fix: allows uploading lottery result update (#4295)
  sites/partners/src/components/listings/PaperListingForm/sections/LotteryResults.tsx
Labels: ready to merge, release

#764 fix: add releaseDate to partner card (#4315)(release)
  sites/partners/src/pages/listings/[id]/lottery.tsx
Labels: ready to merge, release
