Repository housingbayarea/bloom, pull requests merged in 2024-02, with the labels that each got.

#660 fix: foreign language in export
  shared-helpers/__tests__/views/multiselectQuestions.test.ts
  shared-helpers/src/views/multiselectQuestions.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormMultiselectQuestions.tsx
  sites/public/src/components/shared/FormSummaryDetails.tsx
  sites/public/src/lib/helpers.tsx
Labels: ready to merge

#661 Release/2024 02 06
  .circleci/config.yml
  backend/core/src/map-layers/map-layers.controller.ts
  shared-helpers/src/locales/general.json
  shared-helpers/src/views/multiselectQuestions.tsx
  sites/partners/package.json
  sites/public/cypress/e2e/pages/my-applications.spec.ts
  sites/public/package.json
  sites/public/src/components/account/AccountCard.module.scss
  sites/public/src/components/account/AccountCard.tsx
  sites/public/src/components/account/SignUpBenefits.tsx
  sites/public/src/components/account/StatusItem.module.scss
  sites/public/src/components/account/StatusItem.tsx
  sites/public/src/components/shared/CustomIconMap.tsx
  sites/public/src/components/shared/CustomIcons.tsx
  sites/public/src/layouts/forms.tsx
  sites/public/src/pages/account/account.module.scss
  sites/public/src/pages/account/applications.tsx
  sites/public/src/pages/account/dashboard.tsx
  sites/public/src/pages/account/edit.tsx
  sites/public/src/pages/sign-in.tsx
  yarn.lock
Labels: ready to merge

#663 fix: second script to cleanup last applications
  backend/core/src/migration/1707941488208-multiselectTranslationFix2.ts
Labels: ready to merge

#665 fix: update link on smc resource card
  sites/public/src/page_content/jurisdiction_overrides/san_mateo/resources/HavenConnect.md
Labels: ready to merge

#666 feat: creating external listing "stub" for doorway usage
  backend/core/src/listings/listings.controller.ts
  backend/core/types/src/backend-swagger.ts
Labels: prisma rewrite

#668 feat: limit user names allowed
  api/src/services/user.service.ts
Labels: ready to merge

#669 fix: fixes password out of date error messaging
  api/src/services/listing.service.ts
  api/src/utilities/unit-utilities.ts
  api/test/unit/services/listing.service.spec.ts
  shared-helpers/src/auth/catchNetworkError.ts
Labels: 1 review needed

#670 fix: public site fix take 2
  api/src/services/listing.service.ts
  sites/public/src/lib/hooks.ts
Labels: 1 review needed

#671 feat: new endpoint, forgot pwd fix
  api/src/controllers/application.controller.ts
  api/src/dtos/applications/most-recent-application-query-params.dto.ts
  api/src/services/application.service.ts
  api/src/services/auth.service.ts
  api/test/unit/services/app.service.spec.ts
  api/test/unit/services/application.service.spec.ts
  api/test/unit/services/auth.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/public/src/pages/applications/start/autofill.tsx
Labels: ready to merge

#672 fix: add all of the jurisdiction data to external
  api/src/services/listing.service.ts
Labels: ready to merge
