Repository housingbayarea/bloom, pull requests merged in 2024-06, with the labels that each got.

#706 docs: release - updated pr template (#4116)
  docs/pull_request_template.md
Labels: ready to merge

#709 fix: include check for address type (#4136)
  sites/public/src/components/listing/ListingView.tsx
Labels: ready to merge

#712 fix: fallback and refresh translations (#4105)
  api/prisma/migrations/12_add_content_updated_at/migration.sql
  api/prisma/schema.prisma
  api/prisma/seed-staging.ts
  api/src/dtos/listings/listing.dto.ts
  api/src/services/listing.service.ts
  api/src/services/translation.service.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/services/translation.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge

#708 release: fix buttons and other elements from design QA
  sites/partners/src/components/listings/PaperListingDetails/DetailsUnitDrawer.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationDates.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailUnits.tsx
  sites/partners/src/components/listings/PaperListingForm/OpenHouseForm.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ListingPhotos.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/LotteryResults.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx
  sites/partners/src/components/settings/PreferenceDrawer.tsx
  sites/partners/src/pages/application/[id]/review.tsx
Labels: ready to merge

#714 fix: add language to headers (#4148)
  sites/public/src/pages/preview/listings/[id].tsx
Labels: 1 review needed

#713 fix: hcv community updates
  api/src/controllers/script-runner.controller.ts
  api/src/services/script-runner.service.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/types/backend-swagger.ts
Labels: 1 review needed

#716 fix: add missing listing translations
  api/src/services/translation.service.ts
  api/test/unit/services/translation.service.spec.ts
Labels: ready to merge

#702 fix: partner and public matching (#4090)
  api/.env.template
  api/src/services/user.service.ts
  api/test/integration/user.e2e-spec.ts
  api/test/unit/services/user.service.spec.ts
Labels: ready to merge

#718 feat: ami chart import script runner (#4125)
  api/src/controllers/script-runner.controller.ts
  api/src/dtos/script-runner/ami-chart-import.dto.ts
  api/src/modules/script-runner.module.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge

#724 fix: ami import formatting instructions (#4163)
  api/src/services/script-runner.service.ts
Labels: ready to merge, release

#721 feat: lottery toggle and empty state (#4043)
  sites/partners/.env.template
  sites/partners/next.config.js
  sites/partners/src/components/shared/NavigationHeader.tsx
  sites/partners/src/page_content/locale_overrides/general.json
  sites/partners/src/pages/listings/[id]/applications/pending/index.tsx
  sites/partners/src/pages/listings/[id]/index.tsx
  sites/partners/src/pages/listings/[id]/lottery.tsx
  sites/partners/styles/lottery.module.scss
Labels: ready to merge, release

#710 fix: mailing address fix
  api/src/services/listing.service.ts
  api/test/integration/listing.e2e-spec.ts
  sites/partners/src/components/listings/ListingFormActions.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationAddress.tsx
  sites/partners/src/lib/listings/AdditionalMetadataFormatter.ts
  sites/partners/src/lib/listings/BooleansFormatter.ts
  sites/partners/src/pages/listings/[id]/index.tsx
Labels: ready to merge, release

#725 feature: uptake of Seeds Drawer and Dialog
  shared-helpers/__tests__/Timeout.test.tsx
  shared-helpers/package.json
  shared-helpers/src/auth/Timeout.tsx
  shared-helpers/src/views/sign-in/ResendConfirmationModal.tsx
  sites/partners/__mocks__/tabbable.js
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/e2e/default/06-admin-user-mangement.spec.ts
  sites/partners/cypress/e2e/default/07-jurisdictional-admin-user-management.spec.ts
  sites/partners/cypress/e2e/default/08-preference-management.spec.ts
  sites/partners/package.json
  sites/partners/src/components/applications/Aside.tsx
  sites/partners/src/components/applications/PaperApplicationDetails/DetailsMemberDrawer.tsx
  sites/partners/src/components/applications/PaperApplicationForm/FormMember.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormHouseholdMembers.tsx
  sites/partners/src/components/listings/PaperListingDetails/DetailsUnitDrawer.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationDates.tsx
  sites/partners/src/components/listings/PaperListingForm/OpenHouseForm.tsx
  sites/partners/src/components/listings/PaperListingForm/RequestChangesModal.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitForm.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingSelectionCriteria.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ListingPhotos.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/LotteryResults.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/SelectAndOrder.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx
  sites/partners/src/components/settings/PreferenceDeleteModal.tsx
  sites/partners/src/components/settings/PreferenceDrawer.tsx
  sites/partners/src/components/users/FormUserManage.tsx
  sites/partners/src/pages/application/[id]/review.tsx
  sites/partners/src/pages/index.tsx
  sites/partners/src/pages/listings/[id]/applications/index.tsx
  sites/partners/src/pages/settings/index.tsx
  sites/partners/src/pages/users/index.tsx
  sites/partners/styles/overrides.scss
  sites/public/package.json
  sites/public/src/components/account/ConfirmationModal.tsx
  sites/public/src/components/listing/GetApplication.tsx
  sites/public/src/pages/applications/start/choose-language.tsx
  sites/public/src/pages/create-account.tsx
  sites/public/src/pages/verify.tsx
  yarn.lock
Labels: ready to merge, release
