Repository housingbayarea/bloom, pull requests merged in 2025-05, with the labels that each got.

#878 fix: customized site message
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/.env.template
  sites/public/next.config.js
  sites/public/src/layouts/application.module.scss
  sites/public/src/layouts/application.tsx
Labels: ready to merge, release

#875 4572/listings application add integration tests
  sites/partners/__tests__/components/applications/sections/FormAlternateContact.test.tsx
  sites/partners/__tests__/components/applications/sections/FormApplicationData.test.tsx
  sites/partners/__tests__/components/applications/sections/FormDemographics.test.tsx
  sites/partners/__tests__/components/applications/sections/FormHouseholdDetails.test.tsx
  sites/partners/__tests__/components/applications/sections/FormHouseholdIncome.test.tsx
  sites/partners/__tests__/components/applications/sections/FormHouseholdMembers.test.tsx
  sites/partners/__tests__/components/applications/sections/FormMultiselectQuestions.test.tsx
  sites/partners/__tests__/components/applications/sections/FormPrimaryApplicant.test.tsx
  sites/partners/__tests__/components/applications/sections/FormTerms.test.tsx
  sites/partners/__tests__/components/applications/sections/helpers.tsx
  sites/partners/__tests__/pages/listings/[id]/applications/add.test.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormApplicationData.tsx
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormPrimaryApplicant.tsx
Labels: ready to merge, release

#874 feat: public user dashboard integration tests
  sites/public/__tests__/pages/account/dashboard.test.tsx
  sites/public/src/pages/account/dashboard.tsx
Labels: ready to merge

#873 feat: partners unit groups integration
  shared-helpers/__tests__/testHelpers.ts
  shared-helpers/src/locales/general.json
  sites/partners/__tests__/components/listings/PaperListingForm/sections/DetailUnits.test.tsx
  sites/partners/__tests__/pages/listings/[id]/index.test.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailUnits.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitGroupAmiForm.tsx
  sites/partners/src/components/listings/PaperListingForm/UnitGroupForm.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx
  sites/partners/src/components/listings/helpers.tsx
  sites/partners/src/lib/listings/ListingDataPipeline.ts
  sites/partners/src/lib/listings/UnitGroupsFormatter.ts
  sites/partners/src/lib/listings/formTypes.ts
  sites/partners/src/page_content/locale_overrides/general.json
Labels: ready to merge, release

#872 feat: home page regions
  api/tsconfig.json
  shared-helpers/package.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/views/CustomIconMap.tsx
  sites/public/src/components/home/Home.tsx
  sites/public/src/components/home/HomeRegions.module.scss
  sites/public/src/components/home/HomeRegions.tsx
  sites/public/src/components/home/HomeSection.module.scss
  sites/public/src/components/home/HomeSection.tsx
Labels: ready to merge, release

#870 fix: remove token max length (#4833)
  api/src/dtos/auth/confirm.dto.ts
  api/src/dtos/auth/update-password.dto.ts
Labels: ready to merge, release

#871 fix: allow duplication to not copy unit groups (bloom-housing#4823)
  api/prisma/seed-helpers/feature-flag-factory.ts
  api/src/services/listing.service.ts
  api/test/integration/listing.e2e-spec.ts
Labels: ready to merge, release

#888 release: add feature flag for disabling common app (#4791)
  api/prisma/seed-helpers/listing-data/lakeview-villa.ts
  api/prisma/seed-staging.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/__tests__/pages/listings/[id]/index.test.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailApplicationTypes.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationTypes.tsx
Labels: ready to merge, release

#881 fix: region select field
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingDetails.tsx
  sites/partners/src/lib/listings/formTypes.ts
Labels: ready to merge

#841 feat: login with v3 recaptcha (#4091)
  api/.env.template
  api/package.json
  api/src/controllers/auth.controller.ts
  api/src/dtos/auth/login.dto.ts
  api/src/passports/single-use-code.strategy.ts
  api/src/services/auth.service.ts
  api/test/unit/passports/single-use-code.strategy.spec.ts
  api/test/unit/services/auth.service.spec.ts
  api/yarn.lock
  shared-helpers/src/auth/AuthContext.ts
  shared-helpers/src/types/backend-swagger.ts
  shared-helpers/src/views/sign-in/FormSignInDefault.tsx
  shared-helpers/src/views/sign-in/FormSignInPwdless.tsx
  sites/partners/.env.template
  sites/partners/next.config.js
  sites/partners/package.json
  sites/partners/src/lib/users/signInHelpers.ts
  sites/partners/src/pages/_app.tsx
  sites/partners/src/pages/sign-in.tsx
  sites/public/src/pages/_app.tsx
  sites/public/src/pages/sign-in.tsx
  sites/public/src/pages/verify.tsx
Labels: ready to merge, release

#819 release: date field validation and application due date changes
  api/src/dtos/listings/listing-published-update.dto.ts
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/fixtures/minimalListing.json
  sites/partners/cypress/support/commands.js
  sites/partners/src/components/applications/PaperApplicationForm/sections/FormApplicationData.tsx
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailRankingsAndResults.tsx
  sites/partners/src/components/listings/PaperListingForm/OpenHouseForm.tsx
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationAddress.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/ApplicationDates.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/RankingsAndResults.tsx
  sites/partners/src/lib/listings/formTypes.ts
Labels: ready to merge, release

#887 release: add tag for Home Type on listings (#4782)
  api/prisma/seed-helpers/listing-data/blue-sky-apartments.ts
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  sites/public/src/components/account/FavoritesView.tsx
  sites/public/src/components/browse/ListingBrowse.tsx
  sites/public/src/components/browse/ListingCard.tsx
  sites/public/src/components/listing/ListingViewSeeds.tsx
  sites/public/src/components/listing/listing_sections/MainDetails.tsx
Labels: ready to merge, release

#889 release: add additional accessibility features, update all translations (#4854)
  api/src/dtos/listings/listing-feature.dto.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/integration/permission-tests/helpers.ts
  api/test/unit/services/listing.service.spec.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/types/backend-swagger.ts
  shared-helpers/src/utilities/formKeys.ts
  sites/partners/__tests__/pages/listings/[id]/index.test.tsx
  sites/partners/cypress/e2e/default/03-listing.spec.ts
  sites/partners/cypress/fixtures/listing.json
  sites/partners/src/components/listings/PaperListingForm/sections/BuildingFeatures.tsx
  sites/public/src/components/listing/ListingViewSeedsHelpers.tsx
Labels: ready to merge, release

#884 release: FE - public unit groups (#4752)
  api/src/dtos/unit-groups/unit-group-summary.dto.ts
  api/src/utilities/unit-groups-transformations.ts
  api/test/unit/services/listing.service.spec.ts
  api/test/unit/utilities/unit-group-transformations.spec.ts
  shared-helpers/__tests__/views/summaryTables.test.ts
  shared-helpers/src/locales/general.json
  shared-helpers/src/types/backend-swagger.ts
  shared-helpers/src/views/summaryTables.tsx
  sites/public/src/components/browse/ListingCard.tsx
  sites/public/src/components/listing/ListingViewSeeds.tsx
  sites/public/src/components/listing/listing_sections/RentSummary.tsx
  sites/public/src/lib/helpers.tsx
Labels: ready to merge, release

#886 release: add filters for unitGroups (#4799)
  api/prisma/seed-helpers/unit-group-factory.ts
  api/src/services/listing.service.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
Labels: ready to merge, release

#894 release: public neighborhood amenities (#4806)
  shared-helpers/src/locales/general.json
  sites/public/__tests__/components/listing/listing_sections/Neighborhood.test.tsx
  sites/public/src/components/listing/ListingViewSeeds.module.scss
  sites/public/src/components/listing/ListingViewSeeds.tsx
  sites/public/src/components/listing/ListingViewSeedsHelpers.tsx
  sites/public/src/components/listing/listing_sections/AdditionalFees.tsx
  sites/public/src/components/listing/listing_sections/Features.tsx
  sites/public/src/components/listing/listing_sections/Neighborhood.tsx
Labels: ready to merge, release

#895 release: local theming (#4819)
  shared-helpers/package.json
  sites/partners/package.json
  sites/public/package.json
  sites/public/src/pages/_app.tsx
  sites/public/styles/overrides.scss
  yarn.lock
Labels: ready to merge, release

#879 fix: translations + new logic (#4841)
  shared-helpers/__tests__/postmarkString.test.ts
  shared-helpers/src/locales/es.json
  shared-helpers/src/locales/general.json
  shared-helpers/src/locales/tl.json
  shared-helpers/src/locales/vi.json
  shared-helpers/src/locales/zh.json
  shared-helpers/src/utilities/postmarkString.ts
  sites/public/__tests__/components/listing/listing_sections/Apply.test.tsx
Labels: ready to merge, release

#891 feat: company website field (#4807)
  api/prisma/seed-staging.ts
  api/scripts/setup-psql.sh
  api/src/dtos/listings/listing.dto.ts
  api/src/enums/feature-flags/feature-flags-enum.ts
  shared-helpers/src/types/backend-swagger.ts
  sites/partners/src/components/listings/PaperListingDetails/sections/DetailLeasingAgent.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/LeasingAgent.tsx
  sites/partners/src/lib/listings/formTypes.ts
  sites/partners/src/page_content/locale_overrides/general.json
  sites/public/__tests__/components/listing/listing_sections/LeasingAgent.test.tsx
  sites/public/src/components/listing/ListingView.tsx
  sites/public/src/components/listing/ListingViewSeeds.tsx
  sites/public/src/components/listing/listing_sections/LeasingAgent.tsx
  yarn.lock
Labels: ready to merge

#877 release: allow for multiple availability and bedroom filters (#4831)
  api/src/dtos/listings/listings-filter-params.dto.ts
  api/src/enums/listings/filter-key-enum.ts
  api/src/services/listing.service.ts
  api/src/utilities/build-filter.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge, release

#896 release: upgrade axe-core/react (#4723)
  sites/partners/package.json
  sites/partners/src/pages/_app.tsx
  sites/public/package.json
  sites/public/src/pages/_app.tsx
  yarn.lock
Labels: ready to merge, release

#897 release: upgrade ts-loader (#4722)
  api/package.json
  api/yarn.lock
  shared-helpers/package.json
  sites/public/package.json
  yarn.lock
Labels: ready to merge, release

#904 fix: correct bad seed bedroom data
  api/prisma/seed-staging.ts
Labels: bug, ready to merge

#882 release: listing filter by multiselect
  api/src/dtos/listings/listings-filter-params.dto.ts
  api/src/enums/listings/filter-key-enum.ts
  api/src/services/listing.service.ts
  api/test/integration/listing.e2e-spec.ts
  api/test/unit/services/listing.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge, release

#902 Feat: public account application integration tests
  shared-helpers/__tests__/testHelpers.ts
  sites/public/__tests__/pages/account/application/[id]/index.test.tsx
  sites/public/src/components/applications/SubmittedApplicationView.tsx
Labels: ready to merge

#900 fix: open + closed listings tab fix
  sites/public/.env.template
  sites/public/next.config.js
  sites/public/src/lib/hooks.ts
Labels: ready to merge

#880 fix: allow listing approval to be turned off for partners (#4803)
  api/prisma/seed-staging.ts
  api/tsconfig.json
  sites/partners/__tests__/components/listings/ListingFormActions.test.tsx
  sites/partners/src/components/listings/ListingFormActions.tsx
Labels: ready to merge, release

#905 fix: add additional logging to afs job (#1262) (#4872)
  api/src/services/application-flagged-set.service.ts
  yarn.lock
Labels: ready to merge, release

#907 test: seeds designs cypress test suite (#4850)
  .circleci/config.yml
  sites/public/cypress.config.ts
  sites/public/cypress/mockData/applicationData.ts
  sites/public/cypress/support/commands.js
  sites/public/src/components/browse/ListingCard.tsx
  sites/public/src/patterns/SiteHeader.tsx
Labels: ready to merge

#909 fix: jurisdiction unit groups bug fix (#4860)
  sites/partners/src/components/listings/PaperListingForm/index.tsx
  sites/partners/src/components/listings/PaperListingForm/sections/Units.tsx
Labels: ready to merge, release

#912 release: migrate detroit to multiselect questions (#4851)
  api/src/controllers/script-runner.controller.ts
  api/src/dtos/script-runner/data-transfer.dto.ts
  api/src/modules/script-runner.module.ts
  api/src/services/script-runner.service.ts
  api/test/unit/services/script-runner.service.spec.ts
  shared-helpers/src/types/backend-swagger.ts
Labels: ready to merge, release
